version: "3.1"
services:
        mongo-db:
                image: mongo
                restart: always
                env_file:
                        - ./env/vars.env
                ports:
                        - "27017:27017"
                volumes:
                        - /root/docker_instances/mongo:/data/db
        mongo-express:
                image: mongo-express
                restart: always
                ports:
                        - "8081:8081"
                env_file:
                        - ./env/admin.env

