version: "3.1"
services:
        db:
                container_name: postgres-latest
                image: "postgres:latest"
                restart: always
                env_file:
                        - ./env/psql.env
                ports:
                        - "45432:5432"
                volumes:
                        - ./psql/data:/var/lib/postgresql/data
