#!/bin/bash

export XDG_RUNTIME_DIR="/run/user/1000";
notify-send "Timer is set for $1" -i "appointment-soon"


n=$1

for ((i=0; i<${n}; i++));
do
	clear
	echo "Remaining Time $((n-i)) minute(s)"
	sleep 1m 
done


notify-send "Timer $1 minute" -i "weather-few-clouds" 
play ~/Programming/development/secondkbd/shortcut-scripts/alarm-sounds/standard.mp3 
exit 0
